application: tripster-fall14
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /api/(.*)
  script: api/\1

- url: /
  static_dir: html/

libraries:
- name: MySQLdb
  version: "latest"
